USE [master]
GO

/****** Object:  Database [db_gerenciador_jogos]    Script Date: 29/10/2017 19:25:28 ******/
DROP DATABASE [db_gerenciador_jogos]
GO

/****** Object:  Database [db_gerenciador_jogos]    Script Date: 29/10/2017 19:25:28 ******/
CREATE DATABASE [db_gerenciador_jogos]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'db_gerenciador_jogos', FILENAME = N'/var/opt/mssql/data/db_gerenciador_jogos.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'db_gerenciador_jogos_log', FILENAME = N'/var/opt/mssql/data/db_gerenciador_jogos_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [db_gerenciador_jogos].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [db_gerenciador_jogos] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET ARITHABORT OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [db_gerenciador_jogos] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [db_gerenciador_jogos] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET  ENABLE_BROKER 
GO

ALTER DATABASE [db_gerenciador_jogos] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [db_gerenciador_jogos] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [db_gerenciador_jogos] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET RECOVERY FULL 
GO

ALTER DATABASE [db_gerenciador_jogos] SET  MULTI_USER 
GO

ALTER DATABASE [db_gerenciador_jogos] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [db_gerenciador_jogos] SET DB_CHAINING OFF 
GO

ALTER DATABASE [db_gerenciador_jogos] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [db_gerenciador_jogos] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [db_gerenciador_jogos] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [db_gerenciador_jogos] SET QUERY_STORE = OFF
GO

USE [db_gerenciador_jogos]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [db_gerenciador_jogos] SET  READ_WRITE 
GO


